# Generated by Django 5.2.5 on 2025-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_word', models.CharField(max_length=100)),
                ('answer_word', models.CharField(max_length=100)),
                ('question_language', models.CharField(max_length=50)),
                ('answer_language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
