# Generated by Django 5.2.5 on 2025-09-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='quiz_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='vocab.quizlist'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='goal_value',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='vocabulary_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='vocab.vocabularylist'),
        ),
    ]
