# Generated by Django 5.2.5 on 2025-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularylist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
