# Generated by Django 5.2.5 on 2025-09-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='memory_json',
        ),
    ]
