# Generated by Django 5.2.5 on 2025-09-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_quizlist_vocabulary_quiz_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlist',
            name='quiz_name',
        ),
        migrations.AddField(
            model_name='quizlist',
            name='asked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizlist',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizlist',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='quiz_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='vocab.quizlist'),
        ),
        migrations.AddField(
            model_name='usermemory',
            name='is_asked_in_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='goal_type',
            field=models.CharField(choices=[('minutes_per_day', 'Minutes per day'), ('reviews_per_day', 'Reviews per day'), ('quiz', 'Quiz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='vocabulary_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='vocab.vocabularylist'),
        ),
    ]
