# Generated by Django 5.2.5 on 2025-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_remove_studysession_is_active_uservocabularyprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservocabularyprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservocabularyprogress',
            name='vocabulary',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='memory_json',
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='studysession_end_gte_start'),
        ),
        migrations.DeleteModel(
            name='UserVocabularyProgress',
        ),
    ]
