# Generated by Django 5.2.5 on 2025-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_studysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='goal_type',
            field=models.CharField(choices=[('minutes_per_day', 'Minutes per day'), ('reviews_per_day', 'Reviews per day')], max_length=20),
        ),
    ]
