# Generated by Django 5.2.5 on 2025-08-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_remove_uservocabularyprogress_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReviewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_review_counters', to='vocab.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_review_counters', to='vocab.member')),
                ('vocabulary_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_review_counters', to='vocab.vocabularylist')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='vocab_daily_user_id_86880c_idx'), models.Index(fields=['study_session', 'date'], name='vocab_daily_study_s_fdf6c5_idx'), models.Index(fields=['vocabulary_list', 'date'], name='vocab_daily_vocabul_063c47_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('study_session__isnull', False), ('vocabulary_list__isnull', True)), models.Q(('study_session__isnull', True), ('vocabulary_list__isnull', False)), _connector='OR'), name='daily_counter_xor_scope'), models.UniqueConstraint(fields=('user', 'date', 'study_session'), name='uniq_user_date_session'), models.UniqueConstraint(fields=('user', 'date', 'vocabulary_list'), name='uniq_user_date_deck')],
            },
        ),
    ]
