# Generated by Django 5.2.5 on 2025-08-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_useranswer_vocabularylist_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularylist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_json', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocab.member')),
            ],
        ),
    ]
